version: '3.5'

services:
  web:
    image: nginx:alpine
    container_name: blog-web
    restart: always
    environment:
      - VIRTUAL_HOST=$DOMAIN_NAME
      - LETSENCRYPT_HOST=$DOMAIN_NAME
    volumes:
      - $PWD/_site/:/var/www:ro
      - $PWD/vhost.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - traefik

  build:
    image: jekyll/minimal:latest
    container_name: blog-builder
    restart: always
    volumes:
      - $PWD:/srv/jekyll
    command: jekyll build --watch

networks:
  traefik:
    external: true
    name: $NETWORK
