version: '2'

services:
  web:
    image: nginx:alpine
    container_name: blog-web
    environment:
      - VIRTUAL_HOST=${DOMAIN_NAME}
      - LETSENCRYPT_HOST=${DOMAIN_NAME}
    volumes:
      - $PWD/_site/:/var/www:ro
      - $PWD/vhost.conf:/etc/nginx/conf.d/default.conf:ro

  build:
    command: jekyll build --watch
    image: jekyll/minimal:latest
    container_name: blog-builder
    volumes:
      - $PWD:/srv/jekyll

networks:
  default:
     external:
       name: ${NETWORK}